### PR TITLE
Fix issue 140 -> Workaround (pt. 2) JavaParser not being able to resolve Records.

### LINKED ISSUE #140: Analyzer exception when record part of method call argument
To reproduce the issue:

```
public record TestRecord(int id, String name) {}
```

```
class TestClass {

  void dummyMethod() {
    TestRecord recVar = new TestRecord(1, "string");
    test(recVar);
  }
  void test(TestRecord testRecord) {}
}

```

Which yields an IllegalArgumentException:

```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot get a reference type declaration from com.github.javaparser.ast.body.RecordDeclaration
        at com.github.javaparser.symbolsolver.JavaSymbolSolver.toTypeDeclaration(JavaSymbolSolver.java:317)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeDeclaration(JavaParserFacade.java:701)
        at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.tryToSolveTypeUncached(JavaParserTypeSolver.java:287)
        at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.tryToSolveType(JavaParserTypeSolver.java:253)
        at com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.tryToSolveType(CombinedTypeSolver.java:161)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveType(CompilationUnitContext.java:185)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveType(JavaParserTypeDeclarationAdapter.java:151)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveType(ClassOrInterfaceDeclarationContext.java:101)
        at com.github.javaparser.resolution.Context.solveTypeInParentContext(Context.java:154)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractMethodLikeDeclarationContext.solveType(AbstractMethodLikeDeclarationContext.java:122)
        at com.github.javaparser.resolution.Context.solveType(Context.java:97)
        at com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:345)
        at com.github.javaparser.ast.type.ClassOrInterfaceType.lambda$convertToUsage$3(ClassOrInterfaceType.java:352)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:352)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:609)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:642)
        at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserMethodDeclaration.getReturnType(JavaParserMethodDeclaration.java:87)
        at com.github.javaparser.resolution.MethodUsage.<init>(MethodUsage.java:55)
        at com.github.javaparser.resolution.model.typesystem.ReferenceTypeImpl.lambda$getDeclaredMethods$2(ReferenceTypeImpl.java:163)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at com.github.javaparser.resolution.model.typesystem.ReferenceTypeImpl.getDeclaredMethods(ReferenceTypeImpl.java:161)
        at com.github.javaparser.symbolsolver.logic.AbstractTypeDeclaration.getAllMethods(AbstractTypeDeclaration.java:67)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.toMethodUsage(JavaParserFacade.java:407)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:628)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:65)
        at com.github.javaparser.ast.expr.MethodReferenceExpr.accept(MethodReferenceExpr.java:93)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:503)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:350)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:332)
        at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:294)
        at com.infosupport.ldoc.analyzerj.AnalysisVisitor.visit(AnalysisVisitor.java:387)
        at com.infosupport.ldoc.analyzerj.AnalysisVisitor.visit(AnalysisVisitor.java:72)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:118)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:1760)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:45)
        at com.github.javaparser.ast.body.VariableDeclarator.accept(VariableDeclarator.java:145)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.lambda$visit$0(GenericListVisitorAdapter.java:1847)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:1847)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:45)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:1744)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:45)
        at com.github.javaparser.ast.expr.VariableDeclarationExpr.accept(VariableDeclarationExpr.java:114)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:767)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:45)
        at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:73)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.lambda$visit$0(GenericListVisitorAdapter.java:1847)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:1847)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:45)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:297)
        at com.infosupport.ldoc.analyzerj.AnalysisVisitor.visit(AnalysisVisitor.java:266)
        at com.infosupport.ldoc.analyzerj.AnalysisVisitor.visit(AnalysisVisitor.java:72)
        at com.github.javaparser.ast.body.ConstructorDeclaration.accept(ConstructorDeclaration.java:92)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.lambda$visit$0(GenericListVisitorAdapter.java:1847)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:1847)
        at com.infosupport.ldoc.analyzerj.AnalysisVisitor.typeBuilder(AnalysisVisitor.java:116)
        at com.infosupport.ldoc.analyzerj.AnalysisVisitor.visit(AnalysisVisitor.java:129)
        at com.infosupport.ldoc.analyzerj.AnalysisVisitor.visit(AnalysisVisitor.java:72)
        at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:94)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.lambda$visit$0(GenericListVisitorAdapter.java:1847)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:1847)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:45)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:501)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:45)
        at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:126)
        at com.infosupport.ldoc.analyzerj.Analyzer.analyze(Analyzer.java:82)
        at com.infosupport.ldoc.analyzerj.Main.main(Main.java:46)
```

### PR DESCRIPTION
**Pull request by GuusVink**
The previous workaround involved a private method resolve(..) that contained a try/catch mechanism for the UnsupportedOperationException (which was only implemented for types/toResolvedType. The first issue was that this method was not always used in the visitor for resolving types. Secondly, two more methods of resolver were used: resolveDeclaration and calculateType (for expressions). At least the latter of the two also resulted in exceptions regarding JavaParser's inability to handle Records properly.
The implemented solution was to route all calls to the resolver via the resolve method (which now has a general Node as a parameter). So that there is one place where all exceptions thrown concerning records are caught.

Some more notes:

- Now returns "Unknown" instead of the node name as type. As the problem now concerns things such as method call arguments, the name of the argument might not be as relevant as the type name. Furthermore, said name is already included in the respective description so this would only be duplicated.
- Besides UnsupportedOperationException, IllegalArgumentException is also caught. JavaParser throws Unsupported in case the to-be-resolved record is in the same compilation unit, and an IllegalArgument when said record is outside the compilation unit (i.e., same package different file, or other package).
- Now only contains a test parsing the originally failing code (thus failing when it does not analyse properly). It does not check the expected output. Furthermore, It only tests the case of 'Record in same compilation unit'. Testing the outside compilation unit would require setting up a more elaborate construction (i.e., to be parsed files as resources), if I am not mistaken. This feels not that useful to do for such a dirty workaround that relies on a JavaParser issue.

Fixes #140

### CODE REVIEW

File: analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/ldjexceptions/LdocException.java [hunk 1]
```diff
@@ -0,0 +1,15 @@
+package com.infosupport.ldoc.analyzerj.ldjexceptions;
+
+/**
+ * General Exception that can be thrown by the Living Documentation Analyzer.
```
Comment (wandernauta) [inline analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/ldjexceptions/LdocException.java:4]: I don't really follow this one - if it's really a general exception, what does this do that a RuntimeException does not?

When would code that calls the analyzer catch and handle `LdocException`s from the analyzer one way, and handle `RuntimeException`s from the analyzer another way? If that place does not exist, does the difference matter?

Is the intention that the analyzer will, in the future, only throw `LdocException` and nothing else? Or is this really a `MethodThatTakesNodeWasPassedANodeButItsTheWrongKindOfNodeException`, and intended to stay that way?

All in all, for me, this adds more confusion than it clears up; prefer remove.

File: analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java [hunk 2]
```diff
@@ -78,13 +79,27 @@ public AnalysisVisitor(SymbolResolver resolver) {
     this.resolver = resolver;
   }
 
-  /** Resolves the given type to a String with its fully-qualified class name. */
-  private String resolve(Type type) {
+  /** Resolves the given node to a String with its fully-qualified class name.
```
Comment (wandernauta) [inline analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java:82]: Nit: For multi-line Javadoc comments, usually the `/**` gets its own line. The `* */` is not written with a space.

File: analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java [hunk 3]
```diff
@@ -78,13 +79,27 @@ public AnalysisVisitor(SymbolResolver resolver) {
...
+   * Calls the corresponding resolver method based on the type of the node.
+   * */
+  private String resolve(Node node) {
```
Comment (wandernauta) [inline analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java:85]: I'm alright with changing `this.resolve(something)` to be a kind of "look at what something is, and do something sensible based on what it is exactly" method, but I would prefer to do the switching on type by way of overloading:

```
private String resolve(Type t) {
  ...
}

private String resolve(AnnotationExpr ae) {
  ...
}

private String resolve(Expression e) {
  ...
}
```

This is a Visitor, after all - that design pattern is intended to remove the need for `instanceof` checks.

This would also remove the need for the LdocException.

File: analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java [hunk 4]
```diff
@@ -78,13 +79,27 @@ public AnalysisVisitor(SymbolResolver resolver) {
...
+        return resolver.resolveDeclaration(ae, ResolvedAnnotationDeclaration.class)
+            .getQualifiedName();
+      } else if (node instanceof Expression e) {
+        return resolver.calculateType(e).describe();
+      } else {
+        throw new LdocException("The type of node trying to be resolved is not implemented in the "
+            + "AnalysisVisitor.");
+      }
+    } catch (UnsupportedOperationException | IllegalArgumentException e) {
       // References to records can not be resolved yet (issue #66); fall back to unqualified name
```
Comment (wandernauta) [inline analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java:99]: This claims to fall back on unqualified names, but it does not.

File: analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java [hunk 5]
```diff
@@ -78,13 +79,27 @@ public AnalysisVisitor(SymbolResolver resolver) {
...
-      return type.toString();
+      // Apparently, in case the to be resolved Record lies in a separate compiltation unit,
```
Comment (wandernauta) [inline analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java:100]: Typo: compiltation.

File: analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java [hunk 6]
```diff
@@ -384,13 +399,13 @@ public List<Description> visit(MethodCallExpr n, Analyzer arg) {
...
     for (Expression argument : n.getArguments()) {
-      String type = resolver.calculateType(argument).describe();
+      String type = resolve(argument);
       String text = argument.toString();
       arguments.add(new ArgumentDescription(type, text));
     }
     return List.of(
         new InvocationDescription(
-            n.getScope().map(s -> resolver.calculateType(s).describe()).orElse("?"),
+            n.getScope().map(this::resolve).orElse("?"),
```
Comment (wandernauta) [inline analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java:408]: This is now inconsistent - is the fallback string `"Unknown"` or `"?"`? Prefer making them the same - and ideally consistent with upstream, I think there's a `"?"` in `pitstop.analyzed.json`.

**Review by wandernauta — COMMENTED** [review]
First round done, added a few suggestions.

File: analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java (hunk 3 above)
Comment (GuusVink) [reply analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java:85]: I considered your suggestion as well. The main disadvantage of this would be code duplication.

As we work around bug(s) in JavaParser, there is a bit logic that we catch some runtime exceptions and in that case, return a placeholder string. As this logic depends on issues in JavaParser, we rightfully added some comments referring to this issue. In case of method overloading, there would be three methods with duplicates of the same try/catch mechanism, argumentation/reference comment, and 'unknown placeholder' return statements.

We also have to consider that the original resolve method was defined as a workaround for the first encountered bug in JavaParser. At that time, some places in the visitor referred to the resolve method, and some still called the JavaParser directly. In that sense, the resolve method is more of a wrapper to the JavaParser resolver than it is part of the visitor. Following this, if one desires component separation, we could explicitly define a wrapper for the JavaParser resolver that works around the bugs in such a way that it works for LivingDocumentation.


All in all, I still think there are reasons to keep it this way or change it to an entirely different structure altogether,
I am curious whether my argumentation was able to persuade you or whether you still think differently :)

File: analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/ldjexceptions/LdocException.java (hunk 1 above)
Comment (GuusVink) [reply analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/ldjexceptions/LdocException.java:4]: Throwing generic runtime exceptions is, I think, never a good practice. Also, as an exception should be specific, I agree that the current form of this custom exception is not good.

To mitigate this issue properly, I see two options:
1. Change the custom exception to something more specific, e.g., `MethodThatTakesNodeWasPassedANodeButItsTheWrongKindOfNodeException` but preferably a bit more concise
2. Throw an UnsupportedOperation exception with a message stating something like 'not yet implemented' (see https://stackoverflow.com/a/22045192 for a discussion) 

Curious to know how you think about this

File: analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java (hunk 3 above)
Comment (wandernauta) [reply analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java:86]: I am not worried about code duplication in this case, especially since this is, as you say, code that can be removed once JavaParser no longer has this bug.

File: analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/ldjexceptions/LdocException.java (hunk 1 above)
Comment (wandernauta) [reply analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/ldjexceptions/LdocException.java:4]: My preference would be to reshape the `resolve` code to use overloading, as I suggested over there. That way:

* the "it was passed the wrong subtype" case is guaranteed by the compiler not to happen
* no exception needs to be thrown in `resolve` at all
* this class can be removed entirely
* the decision whether it is better to throw an `RuntimeException` or a `MethodThatTakesNodeWasPassedANodeButItsTheWrongKindOfNodeException` can be left to some other time.

File: analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java (hunk 3 above)
Comment (GuusVink) [reply analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java:86]: I think this mechanism will be in place longer than we might hope.

Currently, the record bug in JavaParser has already been open for a long time and manifests in different ways, with no indication that it will be fixed soon. 

I think it comes down to the issue of how we want to handle JavaParser not being able to resolve certain types. Do we want to fail the analyzer, or do we at all times want to provide a result (with "?" in place of the type)?
In the case of the latter, it might be good to just permanently keep the try/catch clause (maybe even catching generic runtime exceptions and log a warning)

Comment (wandernauta) [reply analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java:86]: Sure. We would keep the try/catch clauses as long as JavaParser has this limitation. If JavaParser has the limitation until the end of time, we would keep the try/catch clause until the end of time.

In the meantime, my preference would be to fall back on the unqualified name if possible, I think that is the most likely to be useful. It is also the existing behavior.

Comment (wandernauta) [reply analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java:86]: > I tried to say it might be good to keep the try/catch clause even if all the bugs we currently work around are fixed.

I agree! But that doesn't really affect this PR, right? We can make this decision when that time comes (which, as you said, may not happen soon or may not happen at all). At that point we would reconsider: do we still want these `catch`es? What use is it to us? And if we do want to keep it, we could even think about: are we happy enough with it in its current shape, so with the three overloads, or do we instead want the shape in this PR with the `instanceof` checks and the `throw`, or do we want something else entirely?

But that's then and this is now. For now, falling back on a fixed value seems fine to me, I just don't like the `if` `instanceof` tree.

> For the sake of consistency I changed it to an explicit 'unknown type' ["?" everywhere].

I'm okay with this; consistency is also important.

Comment (GuusVink) [reply analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java:85]: > But that's then and this is now. For now, falling back on a fixed value seems fine to me, I just don't like the `if` `instanceof` tree.

I agree with the fact that the if statement tree is not that pleasing. However, I still think it would be nice to keep this workaround logic in one place as opposed to three separate methods. Especially in case we plan to change the logic, but also in case it stays this way.

For now, if desired, the resolve method can be split into three methods. For the moment, I at least removed the custom LdocException.

Comment (wandernauta) [reply analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java:85]: Yes, please do the split; it's the last thing that's keeping me from approving this PR, otherwise this looks good.

**Review by wandernauta — APPROVED** [review]
