### PR TITLE
Fix annotation with variable declaration

### LINKED ISSUE #147: Annotation to variable declaration included as statement.
Java allows annotation to be attached to variable declarations (`int x = 0;` in for example a method). This expression is not visited in the AnalysisVisitor (as it is, at least not yet, supposed to turn up in the JSON). However, the annotation declaration is visited, thus showing up in the place of a statement in the output JSON.

Consider the example
```
public static void main(String[] args) {
    @SuppressWarnings
    int x = 0;
  }
```
which turns up in the JSON as:
```
"Statements" : [ {
      "Type" : "java.lang.SuppressWarnings",
      "Name" : "SuppressWarnings"
    }]
```

### PR DESCRIPTION
**Pull request by GuusVink**
Simply return null on a variable declaration so that the attached Annotation is not visited and thus not included as a statement.

Fixes #147

### CODE REVIEW

File: analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java [hunk 1]
```diff
@@ -432,4 +433,13 @@ public List<Description> visit(JavadocComment n, Analyzer arg) {
             !commentParams.isEmpty() ? commentParams : null,
             !commentTypeParams.isEmpty() ? commentTypeParams : null));
   }
+
+  /** Describes a Variable Declaration Expression. As these are not supported in the JSON, there is
```
Comment (wandernauta) [inline analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java:437]: Nit: Prefer starting 'Describes' on the next line, for consistency with multi-line Javadoc comments elsewhere.

File: analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java [hunk 2]
```diff
@@ -432,4 +433,13 @@ public List<Description> visit(JavadocComment n, Analyzer arg) {
...
+   * no matching description. This method is explicitly implemented to return null in order to
+   * prevent annotations being visited that are attached to the Variable Declaration.
+   */
+  @Override
+  public List<Description> visit(VariableDeclarationExpr n, Analyzer arg) {
+    return null;
```
Comment (wandernauta) [inline analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java:443]: Prefer returning `List.of()` instead of `null` for consistency with `visit(CatchClause n, Analyzer arg)` - or, alternatively, changing that method to also return `null` in its special case.

File: analyzer-java/src/test/java/com/infosupport/ldoc/analyzerj/AnalysisVisitorTest.java [hunk 3]
```diff
@@ -554,6 +554,29 @@ void annotation_declaration_with_field_no_default() {
...
+
+    List<Description> expected = List.of(new TypeDescription.Builder(TypeType.CLASS, "Test")
+            .withMembers(new MethodDescription(
+                new MemberDescription("main", 0, List.of(), null),
+                null, List.of(new ParameterDescription("java.lang.String[]", "args", List.of())),
+                List.of()
+            ))
+        .build());
+
+    assertIterableEquals(parse(code), expected);
```
Comment (wandernauta) [inline analyzer-java/src/test/java/com/infosupport/ldoc/analyzerj/AnalysisVisitorTest.java:578]: Suggest `parseFragment` here instead of `parse` to make the test a bit shorter. You will need to put at least one statement that's not ignored (say, `return x;`).

**Review by wandernauta — COMMENTED** [review]
This looks like a sensible fix, nice! I've put some small suggestions.

File: analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java [hunk 4]
```diff
@@ -432,4 +433,14 @@ public List<Description> visit(JavadocComment n, Analyzer arg) {
             !commentParams.isEmpty() ? commentParams : null,
             !commentTypeParams.isEmpty() ? commentTypeParams : null));
   }
+
+  /**
+   * Describes a Variable Declaration Expression. As these are not supported in the JSON, there is
+   * no matching description. This method is explicitly implemented to return null in order to
```
Comment (wandernauta) [inline analyzer-java/src/main/java/com/infosupport/ldoc/analyzerj/AnalysisVisitor.java:439]:
```suggestion
   * no matching description. This method is explicitly implemented to return nothing in order to
```

**Review by wandernauta — APPROVED** [review]
Thanks! I've put one comment nitpick, I'll leave it up to you whether you want to fix that before merge.
